### ISSUE TITLE
Relax requests dependency constraint once psf/requests issue 6432 is resolved

### ISSUE THREAD

**Issue by mgyucht** [databricks/databricks-sdk-py#149] opened 2023-06-06 08:15 UTC
Currently we add a strict upper bound of <2.29 to the requests library. Requests 2.30+ is incompatible with urllib <2, but users of databricks-sdk may still depend on older versions of urllib. Once https://github.com/psf/requests/issues/6432 is resolved, we should relax the upper bound to allow more recent versions of the requests library which incorporate the most recent release of urllib. This should improve the security posture of the SDK.

**Comment by judahrand** [comment] 2023-06-08 08:11
>  Requests 2.30+ is incompatible with urllib <2

This isn't true. Read the release notes [here](https://github.com/psf/requests/releases/tag/v2.30.0). They explicitly state that users who need an older `urllib3` can pin it... (`urllib3<2`).

> but users of databricks-sdk may still depend on older versions of urllib

They _may_ depend on it older versions of `urllib` but they also may not. It should be left to consumers of this package to pin their dependencies to a working set.

eg.
```
databricks-sdk
requests>=2.31
urllib3<2
```

Can we **please** either unpin `requests` and leave it up to the consumer to pin `urllib3` if they need to (which is the right answer here) or unpin `requests` but pin `urllib3<2` in this package (less good solution but a compromise!).

**Comment by judahrand** [comment] 2023-06-08 08:12
Additionally, this is a duplicate of #149

**Closed** 2023-06-09 13:10 UTC
