### ISSUE TITLE
[ISSUE] Limit is ignored in jobs.list_runs

### ISSUE THREAD

**Issue by sebbegg** [databricks/databricks-sdk-py#253] opened 2023-07-27 07:56 UTC
**Description**
When using `jobs.list_runs` in combination with a limit, the limit is ignored.
From peeking into the code it seems the `limit` and `offset` arguments are only used for the "internal" page size for listing runs.
But irrespective of the value of `limit`, the functions seems to yield all available runs.

In my case, I only want to retrieve the latest run for a specific job, so I use

```python
latest_run = list(client.jobs.list_runs(job_id=1234, limit=1))[0]
```

What this does though, is doing - in this case - 720 requests, each with a limit of 1 to finally produce 720 runs.
Instead of just the one.

It seems there is no way to really limit the result size at this moment?

From a quick peek into other apis, this pattern seems to exist elsewhere too (e.g. in the `PolicyFamiliesAPI`).

**Reproduction**
As above:

```python

runs = list(client.jobs.list_runs(job_id=..., limit=1))
assert len(runs) <= 1
```

**Expected behavior**
The limit should be respected and/or the documentation adjusted.

**Debug Logs**
The SDK logs helpful debugging information when debug logging is enabled. Set the log level to debug by adding `logging.basicConfig(level=logging.DEBUG)` to your program, and include the logs here.

**Other Information**
* MacOs
* databricks-sdk: 0.2.1

**Additional context**

**Comment by mgyucht** [comment] 2023-07-27 08:47
This reflects the behavior of the REST API. Listing happens lazily, so if you want to limit the number of job runs you've listed, you should combine the returned iterator with something that only returns the number of runs you desire, e.g.
```py
import itertools
itertools.islice(w.jobs.list_runs(job_id=...), 5)
```

**Comment by mgyucht** [comment] 2023-07-27 08:48
Perhaps limit is a bad name; this parameter should really be called "page_size".

**Comment by sebbegg** [comment] 2023-07-27 11:39
Hi,

yes, I've found a workaround using a plain `next`, since I only need the first.
I know the name comes from the rest api, but as you noticed, it is at least surprising behaviour for a code snippet like `list_runs(limit=1)`.

**Comment by mgyucht** [comment] 2023-08-03 08:24
I will give this feedback to our Jobs team; in the meantime, I will close this ticket out, as I believe the issue is resolved.

**Closed by mgyucht** 2023-08-03 08:24 UTC
