### ISSUE TITLE
[ISSUE] Access control list not parsed correctly

### ISSUE THREAD

**Issue by julianfesel** [databricks/databricks-sdk-py#329] opened 2023-08-31 15:40 UTC
**Description**
Creating a new job with an access control list leads to an error:
`TypeError: Object of type AccessControlRequest is not JSON serializable`

It is probably because there is an ".as_dict()" missing here:
https://github.com/databricks/databricks-sdk-py/blob/3bfe1d08b628a1a60a38f2bedbad92af9817dca7/databricks/sdk/service/jobs.py#L2882

**Reproduction**
Using the method WorkspaceClient().jobs.create() with a list of AccessControlRequest like:
```
acl = [AccessControlRequest(
            user_name="funny.user@compa.ny", permission_level=PermissionLevel.CAN_MANAGE
        )]
```

**Other Information**
 - OS: macOS
 - Version: 0.7.0

**Comment by pietern** [comment] 2023-09-06 13:20
Thanks for reporting the issue. We'll take a look.

**Comment by pspeter** [comment] 2023-09-07 12:20
Hi Julian! 
Duplicate of #270 😉

**Comment by mgyucht** [comment] 2023-09-27 13:38
I'm closing this as a duplicate of #270.

**Closed by mgyucht** 2023-09-27 13:38 UTC
Labels: bug
