### ISSUE TITLE
The 'get_status()' on WorkspaceConf does not work.

### ISSUE THREAD

**Issue by xheox** [databricks/databricks-sdk-py#211] opened 2023-06-30 01:20 UTC
**Description**
The 'get_status()' on WorkspaceConf does not work.

**Reproduction**
using this simple code as in the sample 

w = WorkspaceClient()
conf = w.workspace_conf.get_status(keys="enableWorkspaceFilesystem")

**Expected behavior**
This should return a json with the status of the feature passed in the "keys"
the following CURL returns an actual result 
curl  -n https://<host>/api/2.0/workspace-conf?keys=enableIpAccessLists --header "Authorization: Bearer <token>"

the result looks like : 
{"enableIpAccessLists":null}

**Debug Logs**

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<command-3603138930235774> in <cell line: 4>()
      2 
      3 w = WorkspaceClient()
----> 4 conf = w.workspace_conf.get_status(keys=None)

/local_disk0/.ephemeral_nfs/envs/pythonEnv-9db84145-4126-42e9-aa4b-8511b59ec0d9/lib/python3.9/site-packages/databricks/sdk/service/settings.py in get_status(self, keys, **kwargs)
   1182 
   1183         json = self._api.do('GET', '/api/2.0/workspace-conf', query=query)
-> 1184         return WorkspaceConf.from_dict(json)
   1185 
   1186     def set_status(self, **kwargs):

/usr/lib/python3.9/typing.py in __getattr__(self, attr)
    691         # Also for simplicity we just don't relay all dunder names
    692         if '__origin__' in self.__dict__ and not _is_dunder(attr):
--> 693             return getattr(self.__origin__, attr)
    694         raise AttributeError(attr)
    695 

AttributeError: type object 'dict' has no attribute 'from_dict'

**Other Information**
 - executed in notebook in Azure databricks
 - Version: 11.3

**Additional context**
It would be also nice to find a list of all possible values for the "keys" in the documentation. 
https://docs.databricks.com/api/azure/workspace/workspaceconf/getstatus
I am mostly interested in the flag to control the Table Access Control on the workspace level.

**Comment by nfx** [comment] 2023-07-10 10:17
Duplicate of #128

**Closed by nfx** 2023-07-10 10:17 UTC
Labels: bug, codegen
